services:
  php:
    container_name: laravel
    build:
      args:
        USER: ${USER:-www-data}
        UID: ${UID:-1000}
      context: .
      dockerfile: Dockerfile.prod
    image: ticket_php
    volumes:
      - ./:/var/www
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./nginx/test/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/www:/var/www/certbot/
      - ./docker/certbot/conf:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

  scheduler:
    image: ticket_php
    container_name: scheduler
    depends_on:
      - php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["sh", "-c", "while :; do php artisan schedule:run >> storage/logs/cron.log 2>&1; sleep 60; done"]

  worker:
    image: ticket_php
    container_name: worker
    depends_on:
      - php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["php", "artisan", "queue:work"]

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot/
      - ./docker/certbot/conf:/etc/letsencrypt/
    command: certonly --webroot -w /var/www/certbot --force-renewal -d club.barrabasazogues.com --email barrabasclubsistema@gmail.com --agree-tos --non-interactive