services:
  php:
    container_name: laravel
    build:
      args:
        USER: ${USER:-www-data}
        UID: ${UID:-1000}
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    restart: unless-stopped
